<form method="GET" action="{{ route('store.shop') }}" class="grid gap-4">
    <label class="store-label">Search<input class="store-input mt-1.5" name="q" value="{{ request('q') }}" placeholder="Name, SKU or barcode"></label>
    <label class="store-label">Category<select class="store-input mt-1.5" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category') === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
    <label class="store-label">Brand<select class="store-input mt-1.5" name="brand"><option value="">All brands</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(request('brand') === $brand->id)>{{ $brand->name }}</option>@endforeach</select></label>
    <div class="grid grid-cols-2 gap-2"><label class="store-label">Min price<input class="store-input mt-1.5" type="number" min="0" step="0.01" name="min_price" value="{{ request('min_price') }}"></label><label class="store-label">Max price<input class="store-input mt-1.5" type="number" min="0" step="0.01" name="max_price" value="{{ request('max_price') }}"></label></div>
    <label class="store-label">Sort<select class="store-input mt-1.5" name="sort"><option value="newest">Newest</option><option value="price_asc" @selected(request('sort') === 'price_asc')>Price: Low to High</option><option value="price_desc" @selected(request('sort') === 'price_desc')>Price: High to Low</option><option value="name" @selected(request('sort') === 'name')>Name</option></select></label>
    <label class="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" name="in_stock" value="1" @checked(request()->boolean('in_stock')) class="h-4 w-4 rounded border-slate-300 text-indigo-600"> In stock only</label>
    <button class="store-button-primary justify-center py-3">Apply filters</button><a href="{{ route('store.shop') }}" class="text-center text-sm font-semibold text-slate-500">Clear filters</a>
</form>
