@extends('layouts.storefront')
@section('title', 'Checkout | Island Thrift')
@section('content')
<section class="store-container pt-10 sm:pt-14"><span class="store-kicker">Simple and secure</span><h1 class="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Checkout</h1><form method="POST" action="{{ route('store.checkout.place') }}" class="mt-9 grid items-start gap-8 lg:grid-cols-[1fr_380px]">@csrf
<div class="grid gap-6"><section class="store-checkout-panel"><h2>Contact details</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="store-label">Full name<input class="store-input mt-1.5" name="name" value="{{ old('name') }}" required></label><label class="store-label">Phone number<input class="store-input mt-1.5" type="tel" name="phone" value="{{ old('phone') }}" required></label><label class="store-label sm:col-span-2">Email <span class="font-normal text-slate-400">(optional)</span><input class="store-input mt-1.5" type="email" name="email" value="{{ old('email') }}"></label></div></section>
<section class="store-checkout-panel"><h2>Delivery or pickup</h2><div class="mt-5 grid gap-3">@foreach($deliveryMethods as $key=>$label)<label class="store-choice"><input type="radio" name="delivery_method" value="{{ $key }}" @checked(old('delivery_method', array_key_first($deliveryMethods))===$key)><span><strong>{{ $label }}</strong>@if($key==='pickup')<small>Collect from Island Thrift in Himmafushi.</small>@else<small>Delivery is available throughout Himmafushi and to Malé. We will contact you to confirm the details.</small>@endif</span></label>@endforeach</div><label class="store-label mt-5 block">Address / location details<textarea class="store-input mt-1.5" name="delivery_address" rows="3">{{ old('delivery_address') }}</textarea></label></section>
<section class="store-checkout-panel"><h2>Payment</h2><div class="mt-5 grid gap-3">@foreach($paymentMethods as $key=>$label)<label class="store-choice"><input type="radio" name="payment_method" value="{{ $key }}" @checked(old('payment_method', array_key_first($paymentMethods))===$key)><span><strong>{{ $label }}</strong><small>No online payment will be taken on this website.</small></span></label>@endforeach</div><label class="store-label mt-5 block">Order notes <span class="font-normal text-slate-400">(optional)</span><textarea class="store-input mt-1.5" name="notes" rows="3">{{ old('notes') }}</textarea></label></section></div>
<aside class="rounded-3xl bg-slate-950 p-7 text-white lg:sticky lg:top-28"><h2 class="text-xl font-black">Your order</h2><div class="mt-5 grid gap-4">@foreach($items as $item)<div class="flex justify-between gap-5 text-sm"><span class="text-slate-300">{{ $item['product']->name }} × {{ $item['quantity'] }}</span><strong>{{ number_format($item['price']*$item['quantity'],2) }}</strong></div>@endforeach</div><div class="mt-6 flex justify-between border-t border-white/10 pt-5"><span>Total</span><strong class="text-xl">{{ $items->first()['product']->branchPrices->first()?->currency ?? 'MVR' }} {{ number_format($subtotal,2) }}</strong></div><p class="mt-3 text-xs text-slate-400">Delivery charge: MVR 0.00. Any future charges can be configured before activation.</p><button class="store-hero-button mt-6 w-full justify-center">Place Order</button></aside>
</form></section>
@endsection
